# Generated by Django 5.1.4 on 2025-04-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(blank=True, choices=[('furniture', 'Furniture'), ('electronics', 'Electronics'), ('stationery', 'Stationery'), ('tools', 'Tools'), ('cleaning_supplies', 'Cleaning Supplies'), ('other', 'Other')], max_length=100),
        ),
    ]
