# Generated by Django 5.1.4 on 2025-04-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventoryitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrequest',
            name='request_date',
            field=models.DateTimeField(),
        ),
    ]
