# Generated by Django 5.1.4 on 2025-04-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_itemrequest_request_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='maintenance_interval_days',
            field=models.PositiveIntegerField(blank=True, help_text='Number of days after which maintenance is needed (if applicable)', null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='needs_maintenance',
            field=models.BooleanField(default=False),
        ),
    ]
