# Generated by Django 5.1.4 on 2025-04-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventoryitem_maintenance_interval_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='last_maintenance_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
