# Generated by Django 5.1.4 on 2025-04-22 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventoryitem_last_maintenance_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issuer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='issued_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
