# Generated by Django 5.1.4 on 2025-06-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_itemrequest_issued_by_itemrequest_issued_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='last_maintenance_date',
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='last_maintenance_date',
            field=models.DateField(auto_now=True),
        ),
    ]
