# Generated by Django 4.2.7 on 2025-07-03 04:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_inventoryitem_date_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='last_maintenance_date',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='last_maintenance_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
