# Generated by Django 4.2.7 on 2025-07-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_inventoryitem_last_maintenance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrequest',
            name='last_maintenance_date',
            field=models.DateField(auto_now=True, default='2025-07-01'),
            preserve_default=False,
        ),
    ]
