# Generated by Django 4.2.7 on 2025-07-03 05:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_itemrequest_last_maintenance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('furniture', 'Furniture'), ('electronics', 'Electronics'), ('stationery', 'Stationery'), ('tools', 'Tools'), ('cleaning_supplies', 'Cleaning Supplies'), ('other', 'Other')], default='other', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='last_maintenance_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['item_type'], name='inventory_i_item_ty_72ee4a_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['category'], name='inventory_i_categor_fe6a79_idx'),
        ),
        migrations.AddIndex(
            model_name='itemrequest',
            index=models.Index(fields=['status'], name='inventory_i_status_d0b121_idx'),
        ),
        migrations.AddIndex(
            model_name='itemrequest',
            index=models.Index(fields=['request_date'], name='inventory_i_request_23c0b3_idx'),
        ),
    ]
