# Generated by Django 4.2.7 on 2025-07-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_inventoryitem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrequest',
            name='last_maintenance_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
