# Generated by Django 4.2.7 on 2025-07-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_inventoryitem_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancerequest',
            old_name='actual_completion_date',
            new_name='completion_date',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='resolution_notes',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='updated_on',
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('issued', 'Issued'), ('return_requested', 'Return Requested'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
