# Generated by Django 4.2.7 on 2025-07-22 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_rename_actual_completion_date_maintenancerequest_completion_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('reorder_level', models.PositiveIntegerField(default=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='reorder_level',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='item_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.itemgroup'),
        ),
    ]
